dependencies:
  # - <organization/repo>@<version>
  - smartcontractkit/chainlink-brownie-contracts@1.2.0
  - OpenZeppelin/openzeppelin-contracts@4.8.2
compiler:
  solc:
    remappings:
      - "@chainlink=smartcontractkit/chainlink-brownie-contracts@1.2.0"
      - "@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.8.2"
dotenv: .env
networks:
  default: glocal 
  glocal:
    verify: False